name: Link Checker
description: "Detect broken links and report them to Slack"
inputs:
  SITEMAP_URL:
    description: "Entrypoint: All links on all pages in the sitemap will be scanned"
    required: true
  SLACK_WEBHOOK_URL:
    description: "URL that tells Slack which channel should receive the report"
    required: true
  LYCHEE_DIR:
    description: "Working directory for lychee cache and output files"
    required: false
    default: "lychee"
runs:
  using: composite
  steps:
    - name: Restore lychee cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.LYCHEE_DIR }}/.lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - name: Install Lychee
      # third-party action, pin to commit SHA
      uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
      with:
        lycheeVersion: v0.22.0
        args: --version

    - name: Run Sitemap Check and Generate Payload
      id: process-links
      shell: bash
      env:
        SITEMAP_URL: ${{ inputs.SITEMAP_URL }}
        LYCHEE_DIR: ${{ inputs.LYCHEE_DIR }}
      run: |
        set -e

        mkdir -p "$LYCHEE_DIR"
        cd "$LYCHEE_DIR"

        BASE_URL=$(echo "$SITEMAP_URL" | sed -e 's|^[^/]*//||' -e 's|/.*$||')


        # 1. Download and Check
        curl -sSfL "$SITEMAP_URL" | lychee --dump --exclude 'schemas' - | sed 's|http://|https://|g' > urls.txt

        lychee --cache --max-cache-age 1d \
          --max-redirects 5 \
          --verbose \
          --cookie-jar tmp_cookies \
          --exclude '.js|/api/' \
          --format json $(cat urls.txt) > output.json || true  # || true to prevent early exit

        # 2. Merge logic (using a variable to keep the YAML clean)
        MERGE_SCRIPT='
          (.error_map | to_entries | map({
            key: .key,
            value: [.value[] | { url: .url, status_code: .status.code }]
          }) | from_entries) as $errors |
          (.redirect_map | to_entries | map({
            key: .key,
            value: [
              .value[] | 
              .url as $link_url | 
              select(.status.redirects and .status.redirects != []) | 
              (.status.redirects | last) as $dest_url | 
              select($link_url != $dest_url and ($dest_url | startswith($link_url) | not)) |
              { url: $link_url, dest_url: $dest_url }
            ]
          }) | from_entries) as $redirects |
          (($errors | keys) + ($redirects | keys) | unique) | map({
            key: .,
            value: (($errors[.] // []) + ($redirects[.] // []))
          }) | 
          from_entries |
          with_entries(select(.value | length > 0))
        '
        jq "$MERGE_SCRIPT" output.json > merged_issues.json

        # 3. Slack Payload logic
        # We use a single-quoted string for the script to avoid shell expansion
        SLACK_SCRIPT='
          {
            "blocks": [
              {
                "type": "section",
                "text": { 
                  "type": "mrkdwn", 
                  "text": "*LinkChecker* found \(to_entries | map(.value | length) | add) issues on \($base_url):" 
                }
              },
              (to_entries[] | {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ("*<\(.key)|\(.key)>*\n" + ([.value[] | if .status_code then "   ❌ <\(.url)|broken link>" else "   ⚠️ <\(.url)|link> leads to <\(.dest_url)|another destination>" end] | join("\n")))
                }
              })
            ]
          }
        '
        jq --arg base_url "$BASE_URL" "$SLACK_SCRIPT" merged_issues.json > slack_payload.json

        echo ""
        echo "--- DEBUG: SLACK PAYLOAD START ---"
        jq . slack_payload.json
        echo "--- DEBUG: SLACK PAYLOAD END ---"

        # 5. Check if we have issues to report (blocks length > 1 because of header)
        if [ "$(jq '.blocks | length' slack_payload.json)" -gt 1 ]; then
          echo "HAS_ISSUES=true" >> $GITHUB_OUTPUT
        else
          echo "HAS_ISSUES=false" >> $GITHUB_OUTPUT
        fi

    - name: Post results to Slack
      if: steps.process-links.outputs.HAS_ISSUES == 'true'
      # third-party action, pin to commit SHA
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        webhook: ${{ inputs.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload-file-path: ./${{ inputs.LYCHEE_DIR }}/slack_payload.json

    - name: Save lychee cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ${{ inputs.LYCHEE_DIR }}/.lycheecache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
