name: Link Checker Test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      sitemap_url:
        description: "The URL of the sitemap.xml to parse"
        required: true
        default: "https://zfl.bund.de/sitemap-0.xml"
        type: string

jobs:
  link-checker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: test
        uses: ./
        with:
          SITEMAP_URL: ${{ inputs.sitemap_url }}
